# Generated by Django 3.2 on 2023-06-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilet1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': 'Словарь', 'verbose_name_plural': 'Словари'},
        ),
        migrations.AddField(
            model_name='dictionary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
